name: "Dependabot Checks"
version: 2
updates:

# maintain dependencies for pip
- package-ecosystem: pip
  directory: "/"
  target-branch: "main"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
    - "Roman-Supernova-PIT/software-admins"
  allow:
    - dependency-type: direct
    - dependency-type: indirect
  commit-message:
    prefix: "fix: "
  labels:
    - "CI/CD"

# maintain dependencies for github-actions
- package-ecosystem: "github-actions"
  directory: ".github/workflows"
  target-branch: "main"
  reviewers:
    - "Roman-Supernova-PIT/software-admins"
  schedule:
    interval: monthly
  commit-message:
    prefix: "fix: "
  labels:
    - "CI/CD"
  groups:
    actions:
      patterns:
        - "*"