name: "Run template tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@930ac90540ecc5f43ba6d3d176efd25cd5f3c6c2  # v2.2.2
    with:
      envs: |
        - linux: py311-test
        - linux: py312-test
        - linux: py313-test
        - linux: build-docs
